#! /bin/bash

echo "Enter an integer between 2 and 25 -> "
read depth

while [ $depth -lt 2 ]  || [ $depth -gt 25 ]
do
	echo "Can you count? I said between 2 and 25-> "
	read depth
done

echo

#Top half of diamond
for ((i=0; i < $depth; ++i))
do
	#pad extra spaces
	for ((j=0; j < `expr $depth - $i`; ++j))
	do
		printf " "
	done
	#print the number of stars corresponding to the row
	#we're on. Row num is denoted by $i
	for ((k=0; k <= $i; ++k))
	do
		printf "* "
	done
echo
done

#Bottom half of diamond
for ((i=$depth; i > 0; --i))
do
	#pad extra spaces
	for ((j=-1; j < `expr $depth - $i + 1`; ++j))
	do
		printf " "
	done

	#print the number of stars corresponding to the row
	#we're on. Row num is denoted by $i
	for ((k=1; k < $i; ++k))
	do
		printf "* "
	done

echo
done

