#! /bin/bash

cd temp
files=$(find *)

for file in $files
do
	IFS='-' read -r -a new_name <<< "$file"

	#change the first part of the string to uppercase
	x=$(echo ${new_name[0]} | tr "[a-z0-9]" "[A-Z0-9]")

	#change the second part of the string to lowercase
	y=$(echo ${new_name[1]} | tr "[A-Z0-9]" "[a-z0-9]")
	
	#change the file name
	mv $file $x-$y 2> /dev/null
done
